### ISSUE TITLE
[[Set]] or [[DefineOwnProperty]]?

### ISSUE THREAD

**Issue by Loirooriol** [tc39/proposal-object-from-entries#2]
[`Array.from`](http://www.ecma-international.org/ecma-262/8.0/#sec-array.from) creates properties with [CreateDataPropertyOrThrow](http://www.ecma-international.org/ecma-262/8.0/#sec-createdatapropertyorthrow), which relies on [[DefineOwnProperty]].

[`Object.assign`](http://www.ecma-international.org/ecma-262/8.0/#sec-object.assign) uses [Set](http://www.ecma-international.org/ecma-262/8.0/#sec-set-o-p-v-throw), which relies on [[Set]].

Which one is more appropriate for `Object.fromEntries`?

**Comment by bathos** [comment]
I think you’re correct, `CreateDataPropertyOrThrow` is likely more appropriate because we already know the target object has no special [[Set]] behaviors to account for.

**Comment by Loirooriol** [comment]
https://github.com/bakkot/object-from-entries/blob/53993dcbfca226d3f91d5b83a41d9657be2fa7ee/DETAILS.md#L102-L104

@bakkot [[DefineOwnProperty]] is not consistent with `Object.assign`, which does trigger setters on `Object.prototype`.

**Comment by mathiasbynens** [comment]
@Loirooriol Object spread (`{ ...object }`) does not trigger setters.

**Comment by Loirooriol** [comment]
@mathiasbynens I know, and I prefer it if `Object.fromEntries` does not trigger setters either, but `Object.assign` does, and DETAILS.md says it doesn't.

**Comment by bakkot** [comment]
@Loirooriol Whoops, thanks, fixed.
