### ISSUE TITLE
Championing

### ISSUE THREAD

**Issue by bakkot** [tc39/proposal-object-from-entries#3]
Has this been presented to TC39? I'd be interested in picking it up and championing it, if not.

(I'm a representative on TC39, in case that wasn't clear.)

**Comment by ljharb** [comment]
I'd indicated to @bathos that I'd champion it when I had time; @bakkot, if you have time to do so, I'd love to be a co-champion with you.

**Comment by bathos** [comment]
@bakkot awesome! I’m unsure what next steps would be — let me know if I should either add you as collaborator or transfer ownership of the repo to you.

**Comment by bakkot** [comment]
@bathos It might be easiest if you transfer ownership to me, so I can later transfer it to the tc39 organization without further coordination, but either way works. I suppose I should ask for write access one way or another, as champion; I probably want to reorganize a bit before the meeting, too.

**Comment by bathos** [comment]
@bakkot transfer request sent!

**Comment by bakkot** [comment]
We seem to be moved! Thanks much.

**Comment by bathos** [comment]
@bakkot Should this be on the https://github.com/tc39/proposals/blob/master/stage-0-proposals.md list now that it’s on a meeting agenda?

**Comment by bakkot** [comment]
Yes it should! [Done](https://github.com/tc39/proposals/pull/124), thanks for the reminder.

Hopefully it'll only be there for about a week.
