### ISSUE TITLE
Object.assign cannot be used for the same effect

### ISSUE THREAD

**Issue by Loirooriol** [tc39/proposal-object-from-entries#30]
DETAILS.md says that `Object.assign` can be used to bypass some limitations "for the same effect".

https://github.com/tc39/proposal-object-from-entries/blob/825740ac9ebdceeae5a1a8003a5dbdde341dc1c2/DETAILS.md#L79-L83

But `Object.assign` uses [[Set]] instead of [[DefineOwnProperty]], so it's not the same. It should say one of

```js
Object.setPrototypeOf(Object.fromEntries(entries), proto);
Object.defineProperties(Object.create(proto), Object.getOwnPropertyDescriptors(Object.fromEntries(entries)));
({__proto__: proto, ...Object.fromEntries(entries)}); // Requires B.3.1
```

https://github.com/tc39/proposal-object-from-entries/blob/825740ac9ebdceeae5a1a8003a5dbdde341dc1c2/DETAILS.md#L95-L99

Same problem, it should say

```js
Object.defineProperties(obj, Object.getOwnPropertyDescriptors(Object.fromEntries(entries)));
```

Or instead of "for the same effect", "for a similar effect".

**Comment by bakkot** [comment]
Fixed in 16433a2. Thanks for pointing it out.
