### ISSUE TITLE
Allowing only strings as keys is harmful

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-object-from-entries#5]
The prohibition of non-string keys seriously reduces the capabilities of this proposal.

For example, keys could be numbers or objects with redefined `toString` method:
```js
class Unit {
  constructor(id) {
    this.id = id;
  }
  toString() {
    return `unit${ this.id }`;
  }
}

const units = new Set([new Unit(101), new Unit(102), new Unit(103)]);

Object.fromEntries(units.entries());
```

The prohibition of symbols also looks strange - they could be useful in some cases too.

In my opinion, keys validation step definitely should be removed and keys should use `ToPropertyKey` abstract operation.

**Comment by ljharb** [comment]
Yes, this is something that needs fixing. The check should change to use ToPropertyKey.

**Comment by bathos** [comment]
@zloirock I think that’s reasonable & def agree on reflection. The initial choice was conservative and informed by discussion that led up to the proposal which placed an emphasis on the importance of symmetry between Object.entries and Object.fromEntries, i.e. such that the following would hold true:

```js
const obj1 = Object.fromEntries(entries);
const obj2 = Object.fromEntries(Object.entries(obj1));

assertSameKeysAndValues(obj1, obj2);
```

Achieving that only would require disallowing symbols, not being strict about strings. So perhaps this is two issues, and the "only strings" part should def change but I’m not as certain about "not symbols".

**Comment by ljharb** [comment]
That Object.entries only produces strings is consistent with Object.keys; Object.fromEntries should accept anything since that’s what Map.prototype.entries, for example, could provide. (Also note, Array.prototype.entries provides numeric keys)

**Comment by bathos** [comment]
Aight then, seems like removing both constraints is the way to go.
