### ISSUE TITLE
Consider throwing an error on null / undefined

### ISSUE THREAD

**Issue by zloirock** [tc39/proposal-object-from-entries#6]
For consistency with `Array.from` which throws on `null` / `undefined`.

**Comment by bathos** [comment]
That makes sense; I can’t think of any existing intrinsics that permit null/undefined in place of an iterable argument other than the Map and Set constructors.

(I’m fuzzy on whether there’s been a trend towards permissiveness in these cases; Object.assign/object spread made me suspect that there was.)

**Comment by ljharb** [comment]
I think permissiveness makes sense with multiple arguments, but not as much with one.

**Comment by tophf** [comment]
I doubt this is a good idea: other Object methods mentioned above don't throw on their source argument being falsy so having an exception based on usage assumptions that aren't immediately obvious is adding to the weirdness of the language. It'd be much easier to remember that Object methods consistently don't throw on their source being falsy.

**Comment by ljharb** [comment]
@tophf `Object.keys(null)` throws, `Object.values(null)`, `Object.entries(null)` throws - this is the thing you should already remember, so the easier thing is for `Object.fromEntries(null)` to throw.

**Comment by bakkot** [comment]
Throwing also matches [very nearly all other uses of the iteration protocol](https://github.com/tc39/ecma262/pull/1069#issuecomment-360043550), including most relevantly `Array.from`.

I don't think it's a good idea to model which functions throw based on where they happen to be located. Better that there's consistency between kinds of function, wherever they happen to be. `Object.fromEntries` is unlike all other current Object static methods in that it takes an iterable, rather than an object.

**Comment by bathos** [comment]
@tophf I get where you’re coming from, but that’s not the prevailing pattern. The rule of thumb is not about falsiness, it’s about non-nullishness. Primitives other than undefined and null can be coerced to objects, but null and undefined cannot be boxed. `Array.from` is another example of this. See the [`ToObject`](https://tc39.github.io/ecma262/#sec-toobject) operation, which is used in lots of intrinsic operations.

**Comment by bathos** [comment]
whoa bakkot, near simultaneous there haha

**Comment by tophf** [comment]
> Object.keys(null) throws, Object.values(null), Object.entries(null)

This parameter is the object itself which is being operated on, not the source data parameter for a future object to be created so the relevant examples are Object.assign's 2nd parameter and object spread's source.

**Comment by ljharb** [comment]
@tophf fair. that's when https://github.com/tc39/proposal-object-from-entries/issues/6#issuecomment-409827256 applies :-)

**Comment by tophf** [comment]
Furthering the thought, Object.assign's 2nd parameter and object spread's source can be null or undefined as well as falsy. I consider only these two cases relevant to the topic's case.

**Comment by ljharb** [comment]
Object.assign takes objects. Object.fromEntries takes an iterable - everything that takes an iterable throws on null or undefined.

**Comment by tophf** [comment]
>Object.fromEntries is unlike all other current Object static methods in that it takes an iterable, rather than an object.

This is that nonobvious implementation detail I mentioned. Which is why I think it shouldn't be the deciding factor here.

**Comment by bathos** [comment]
As ljharb pointed out, `assign` is variadic — all arguments are optional, hence that behavior.

(Edit: second redundant comment on account of not seeing the latest updates while I’m typing, derp)

**Comment by tophf** [comment]
>assign is variadic — all arguments are optional, hence that behavior.

Also an implementation detail, which shouldn't drive the high level design of the language.

**Comment by bathos** [comment]
@tophf Would you agree that consistency should be a factor in design decisions?

**Comment by tophf** [comment]
Yes. You seem to value the internal implementation consistency but I think it's secondary to the perceived consistency which is why I'm disagreeing.

**Comment by bathos** [comment]
If something is observable, its _implementation detail-ness_ is subjective — that undefined and null cannot be coerced to objects is not a super obscure detail, imo, nor is the fact that nearly all intrinsic methods attempt coercion. But this isn’t where I was going — what I wanted to suggest is that I believe consistency with `Array.from` is the strongest guide.

**Comment by tophf** [comment]
Okay, I see my suggestion is not objectively any better so as long as fromEntries doesn't throw on [] input I'm fine with the current behavior as we'll be able to use `|| []` fallback if needed.
