### ISSUE TITLE
Should array-like argument be permitted?

### ISSUE THREAD

**Issue by bathos** [tc39/proposal-object-from-entries#9]
Currently it’s expected that the argument to `Object.fromEntries` be an iterable in the `Symbol.iterator` sense.

The `Array.from` and `%TypedArray%.from` methods permit array-like arguments; they fall back on looking for an appropriate length property and numeric keys. Because the ToLength operation coerces most values to 0, this means that they will also accept most objects:

`Array.from({})` // []
`Array.from({ length: 1 })` // [ undefined ]
`Array.from({ length: Infinity })` // RangeError

My sense (which might be wrong) is that support for array-likes was a way to help bridge the gap with pre-ES2015 APIs. Should a new "from" method also support array-likes, or should it be limited to formal iterables like the Map and Set constructors?

See https://github.com/bathos/object-from-entries/pull/8#discussion_r173343027

**Comment by ljharb** [comment]
This is a good question, but I don't think it's actually necessary to accept arraylikes.

**Comment by zloirock** [comment]
See this issue https://github.com/tc39/proposal-setmap-offrom/issues/3

**Comment by bathos** [comment]
Great link! Closing, seems clear that genuine iterables are all we should accept.
